# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(557, 324)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 0, 381, 61))
        self.label.setStyleSheet("background-color: rgb(33, 66, 138);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.inputTextEdit = QtWidgets.QTextEdit(Form)
        self.inputTextEdit.setGeometry(QtCore.QRect(10, 110, 531, 151))
        self.inputTextEdit.setObjectName("inputTextEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 111, 31))
        self.label_2.setObjectName("label_2")
        self.btn_convert = QtWidgets.QPushButton(Form)
        self.btn_convert.setGeometry(QtCore.QRect(10, 280, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_convert.setFont(font)
        self.btn_convert.setObjectName("btn_convert")
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setGeometry(QtCore.QRect(280, 280, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.combo_voice = QtWidgets.QComboBox(Form)
        self.combo_voice.setGeometry(QtCore.QRect(410, 70, 121, 22))
        self.combo_voice.setObjectName("combo_voice")
        self.combo_voice.addItem("")
        self.combo_voice.addItem("")
        self.combo_voice.addItem("")
        self.combo_voice.addItem("")
        self.combo_voice.addItem("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 70, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.label_4.setStyleSheet("background-color: rgb(33, 66, 138);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img/text.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(130, 10, 41, 41))
        self.label_5.setStyleSheet("background-color: rgb(33, 66, 138);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("img/sound.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 41, 41))
        self.label_6.setStyleSheet("background-color: rgb(33, 66, 138);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("img/arrow.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 191, 61))
        self.label_7.setStyleSheet("background-color: rgb(33, 66, 138);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.label.raise_()
        self.inputTextEdit.raise_()
        self.label_2.raise_()
        self.btn_convert.raise_()
        self.btn_cancel.raise_()
        self.combo_voice.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Convert Text To Sound</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Input Text</span></p></body></html>"))
        self.btn_convert.setText(_translate("Form", "Convert To Sound"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))
        self.combo_voice.setItemText(0, _translate("Form", "alloy"))
        self.combo_voice.setItemText(1, _translate("Form", "echo"))
        self.combo_voice.setItemText(2, _translate("Form", "fable"))
        self.combo_voice.setItemText(3, _translate("Form", "onyx"))
        self.combo_voice.setItemText(4, _translate("Form", "nova"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Choose Voice</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
